### ISSUE TITLE
Recommended Enhancements

### ISSUE THREAD

**Issue by edwardlennonjr** [OOW/bigpicture#18]
1.	Adding input boxes with the scroll bar for the minimum and maximum y-axes ranges would make setting exact values easier.  Just like the x-axes section.  It's difficult to zoom in. (e.g. flow range is 1 to 150 and you want to zoom into 1 to 3 to see the baseflow.) 

2.	Adding custom x and y-axis labels and ranges to the scatter plots.  The same labels from the time series plots can be used but the y-axes ranges will probably need their own section. Is it possible to label the y-axes on the left side (like the line plots) and add plot titles?  

3.	How are the color schemes chosen for the scatter plots?  When looking at time divisions of more than 2-3 (like quarters or months) it becomes difficult to tell the periods apart.  Maybe add an option to select different color schemes or themes, or be able to manually change the color of any parameter.         

4.	Can you adjust the line plots so that the y-axes range cuts off the data and is flush with the border?  This will allow you to visually be aware that the y-axis has been adjusted to hide data.  Difficult to explain I know, just ask.

5.	Adding field points, especially for the scatter plots will be important.

6.	Moving Average Section;
a.	Have an option that ignores missing data in the moving average.  For example, when performing a 30 day moving average, the corrected.flow and corrected.level plots are missing some months due to missing data.  If the user chooses to ignore missing values then the entire time series will be filled in.  Setting an option to select the threshold for what percentage of data is required within the moving average range (e.g. calculate an moving average if 75% of data is available, so if 1 week of a month is missing, the monthly average will calculate). 
b.	Can an option be created that removes days with rainfall (+- a certain number of days, 1 or 2 days) from the average?  This will become the dry weather average.
c.	An option to export the moving average time series to a csv file.    

7. Expand the moving average to include years, or days up to 365 pretty please.

8. If possible, include duplicate y-axes labels on the right side of the plot in addition to the left.  

9. When plotting long time periods (5 years), the x-axes month labels on the bottom overlap.  Display as 45 degree angle would work.

**Comment by siddhanathan** [comment]
All the above (except 8) is in master. Closing the issue as fixed.
