### ISSUE TITLE
Bug Report; Version downloaded on 12/22/2014

### ISSUE THREAD

**Issue by edwardlennonjr** [OOW/bigpicture#19]
1) With sample data set;  If you change the start date to 05/01/2014 00:00 (zoom into the last month of data), the following error occurs when apply is clicked.  If the dates are changed around then it eventually works but the source of the error is still unknown to me.  

Error in data.frame(x = structure(numeric(0), class = c("POSIXct", "POSIXt" : 
  arguments imply differing number of rows: 0, 1

2) With the sample data set, using the custom scatter time division.
So I wanted to create a scatter plot that contains 2 months of data in one series and 4 days in the second series.  When I added the two following time periods the smaller period if hidden by the large period.  If I try to switch their order in the list then the smaller period disappears.
2014-04-01;2014-06-01 - 2 months
2014-04-18;2014-04-22 - 4 days within the 2 months

3) Download button does nothing when clicked.

**Comment by siddhanathan** [comment]
Part 1 should be fixed. Still not sure about what to do about part 2. The rule right now is, the later period dominates over a previously entered period, which is why you are noticing that.
