### ISSUE TITLE
Notes 2/20/2015

### ISSUE THREAD

**Issue by edwardlennonjr** [OOW/bigpicture#20]
1) Fails when a parameter is picked that doesn't have an associated field point.

Error in state$ylabels[[flows]] : attempt to select more than one element
Error: geom_point requires the following missing aesthetics: y

2) Remove horizontal lines on field points.  Maybe change the color of the points for they stand out.

Remove lines 758-762; (and other sections)
                              geom_segment(aes(x=field_points_df$DDATE,
                                               y=c(-Inf),
                                               xend=field_points_df$DDATE,
                                               yend=c(Inf)),
                                           field_points_df, environment=.e)

3) Option to remove field points from plots (check box)

4) Moving Average Section
a) Extend the maximum for "Days" value to 365 (calculate the yearly average).
b) The dry weather calculation is incorrect.  We need to remove all time steps within a day where any rainfall occurred. e.g.  It rained on 1/1/2015 at 12:00, 12:15, 12:30, etc; remove all time steps with the date of 1/1/2015 (the entire day).  Currently it looks like it removes matching timesteps.
c) when the moving average is removed, the previously removed wet days don't return.

**Comment by siddhanathan** [comment]
All the above should now be fixed. Try out the new version.

Errors like the first one mentioned, should hopefully not occur once we have the test suite up and running.
