### ISSUE TITLE
Test Notes 2/24/2015

### ISSUE THREAD

**Issue by edwardlennonjr** [OOW/bigpicture#21]
1) I received this error when setting "Select Flow Parameter to use on the x-axis" to corrected.level  or corrected.flow. Assume it's related to missing field points for them.

Error in `[.data.frame`(x, r, vars, drop = drop) : 
  undefined columns selected

2) Plot download button doesn't respond when clicked.

**Comment by edwardlennonjr** [comment]
1) Now it gives the error (Error in eval(expr, envir, enclos) : object 'x' not found) when correct.level or corrected.flow are selected for the x axis in scatter.

2) Download plot button works in Crome but not RStudio.

**Comment by siddhanathan** [comment]
Should be fixed now.
