### ISSUE TITLE
Notes 2/25/2015

### ISSUE THREAD

**Issue by edwardlennonjr** [OOW/bigpicture#22]
No errors that I could find.  It might just be in my head, but I think Crome works slightly faster.  

Here are some comments of bugs, nothing new though.
1) Unable to see field points on scatter plot. Maybe try larger triangle shaped points.  If there are too many and block the rest of the data, try reducing the sample field points to 2 a months (more realistic).

2)  I tested with Rstudio and Crome.  I noticed the crazy plot height a few times in RStudio (clicking apply fixes it) but not in Crome.

3) e.g. when picking corrrected.flow and corrected.level; the first plot is labeled as "level" but appears to plot the correct data. The second plot is labeled as "velocity".   
I think we looked at this weird bug yesterday. 

4) I recommend removing the scatter plot that plots the same parameter on the x and y.  This cleans it up since that type of plot is useless.

**Comment by siddhanathan** [comment]
1, 3 and 4 are fixed. 2 will probably be marked as won't fix, since cross browser compatibility is hard.

**Comment by edwardlennonjr** [comment]
nice, works good!
