### ISSUE TITLE
Scatter plot with only 1 column

### ISSUE THREAD

**Issue by edwardlennonjr** [OOW/bigpicture#32]
Add an index column 1,2,3,...  to plot on the x-axis on the scatter plot.  Make this a checkbox that the user can select in the scatter section.

**Comment by mplourde** [comment]
Updated so that Index is a selectable X-axis name for the scatter plot.

**Comment by edwardlennonjr** [comment]
This is basically the line plot.  I'm not sure what state of mind I was in when I wrote this or the purpose.  I say just leave it because it makes pretty art.
![pretty art](https://cloud.githubusercontent.com/assets/8989544/8196209/44d1065a-1457-11e5-8b62-6b64fd54d134.png)
