### ISSUE TITLE
Allow irregular timesteps

### ISSUE THREAD

**Issue by edwardlennonjr** [OOW/bigpicture#37]
Program fails if there are more than 1 timestep present in data-set.  Is this a necessary feature? Required for moving average?  Some large data sets (especially Telog data) may have irregular timesteps. e.g. 2 years of 2.5 minute data, then a few months of 1 minute data, then back to 2.5 minute.  We want the program to take this data and plot with warnings about irregular timestep. Possibly an output file summarizing the timesteps. e.g. start to end dtime is 2.5 minute data

**Comment by mplourde** [comment]
Yes, it's for the moving average. I'll just disable the ma when there are irregular timesteps.
