### ISSUE TITLE
Moving Average Line plot Update

### ISSUE THREAD

**Issue by edwardlennonjr** [OOW/bigpicture#40]
The following image is for data (not sample) with wet wet weather removed and a 1 day moving average.  This plot is difficult to read, maybe add lines connecting the points.
![dry_weather_1_day_moving_average](https://cloud.githubusercontent.com/assets/8989544/8008627/5fff7266-0b71-11e5-96bc-de66c15dae7e.PNG)

**Comment by mplourde** [comment]
Line colors will be black in the next release, which should make this plot easier to read. Can we re-visit this issue at that time? If it is still hard to read, I can add a layer with low opacity of the original data behind the dry weather sections. In fact, if this sounds like something you'd like, I can just do this in the next release.

**Comment by mplourde** [comment]
Dry weather periods will now be connected with a line.
