### ISSUE TITLE
Layered time series on different y-axes

### ISSUE THREAD

**Issue by edwardlennonjr** [OOW/bigpicture#52]
Be able to choose if the time series is plotted on the left or right y-axes.  This will require two filter sections per plot and two label sections.  If possible more than two y-axes would be great, most people are scarred by Excel's 2 y-axes limitation.

**Comment by mplourde** [comment]
ggplot doesn't support multiple y-axes from a philosophical point of view (see Hadley's answer [here]( http://stackoverflow.com/questions/3099219/how-to-use-ggplot2-make-plot-with-2-y-axes-one-y-axis-on-the-left-and-another)). Although I don't really care and would happily make a double y-axis plot for anyone who asked, adding all the extra controls to support this would really clutter up the interface. We could make Bigpicture as complicated as we want, but at some point we have to draw the line and say, "if you want that, we need to make a custom script".

**Comment by edwardlennonjr** [comment]
We'll consider this NA for this program
